export const postList = [
  {
    id: 1,
    title: "피드백 부탁드립니다",
    content: "안녕하세요, 피드백 부탁드립니다...",
    author: "홍길동",
    views: 42,
    date: "2024-01-20",
  },
  {
    id: 2,
    title: "이 전략이 맞나요?",
    content: "제가 생각한 전략인데 의견 부탁드립니다...",
    author: "김철수",
    views: 128,
    date: "2024-01-19",
  },
  {
    id: 3,
    title: "초보자 가이드 공유",
    content: "제가 처음 시작할 때 도움이 되었던 팁들을 공유합니다.",
    author: "이영희",
    views: 256,
    date: "2024-01-18",
  },
  {
    id: 4,
    title: "패치 1.2 업데이트 후기",
    content: "새로운 패치 이후 달라진 점을 정리해보았습니다.",
    author: "박지성",
    views: 89,
    date: "2024-01-17",
  },
  {
    id: 5,
    title: "팀원 구합니다",
    content: "함께 게임할 팀원을 찾고 있습니다...",
    author: "최민수",
    views: 67,
    date: "2024-01-16",
  },
];
